//Q-1 :- Store two integers in two variables x and y. Print the sum of the two.
 /*
let x= 5;
let y= 6;
let z= x+y;
console.log("the sum of x and y is " + (z));
*/

//Q-2 :- Store two integers in two variables x and y. Print the product of the two.

let x = 6;
let y= 9;
let z = x*y;
console.log("the product of x and y is " +(z));

//Q-3 :- Calculate the average of 5 subjects
let eng = 92;
let hindi = 96;
let maths = 89;
let science = 75;
let sst = 97;
let avg = (eng + hindi + maths + science + sst) / 5;
console.log("The average of 5 subject is : " + avg );

//Q-4 :- Calculate area of Circle,square,rectangle,triangle
let r = 5;
let circle = 3.14 * r* r;
console.log("the area of circle is : " + circle);

let a = 4;
let square = a*a;
console.log("the area of square is : " + square);

let l = 6;
let b = 7;
let h = 8;
let rectangle = l*b*h;
let triangle = (b * h) / 2;
console.log("the area of triangle is : " + triangle);
console.log("the area of rectange is : " + rectangle);

//Q-5 :- Calculate the simple interest
let P = 2000;
let R = 40;
let T = 5;
let SI = (P * R * T) / 100;
console.log("The simple intrest will be : " + SI);

//Q-6 :- Calculate the circumference of circle
let radius = 8;
let circ = 2 * 3.14 * radius;
console.log("The circumference of the circle is : " + circ);

// Q-7 :- Write a program of all the arithmetic operations of Javascript of any two numbers stored in a variable num1 and num2. Also, print the result to the console.

let i = 6;
let j = 9;
console.log("The sum of i and j is " + (i + j));               //15
console.log("The difference of i and j is " + (i - j));        //-3
console.log("The multiplication of i and j is " + (i * j));    //54
console.log("The division of i and j is " + (i / j));          //0.6666
console.log("The modulus of i and j is " + (i % j));           //6
